### ISSUE TITLE
introduction generale

### ISSUE THREAD

**Issue by Ced2014** [F-Consulting/Kit_formation#11]
Bonsoir monsieur.
Jetez un coup d'oeil svp
[INTRODUCTION.docx](https://github.com/F-Consulting/Kit_formation/files/1540390/INTRODUCTION.docx)

J'attends vos remarques merci d'avance
Bonne soiree

**Comment by fots** [comment]
C'est un bon début ... plusieurs fautes ... mais je suis ok pour ce premier jet ... on arrange dimanche. 
Je te conseille un plan en 4 chapitres.
Chapitre 1: etat de l'art, en trois principales sections
Chapitre 2: analyse, puis chapitre 3 conception et chapitre 4 mise en oeuvre
